### ISSUE TITLE
Issue on mobile!!!21311

### ISSUE THREAD

**Issue by SimonSahlen** [frippz/switch-tool#1]
On mobile, it scrolls up when toggling a port. This makes it very difficult for me to toggle alot of ports on switch #3.

Pls fix.

**Comment by frippz** [comment]
That poor alot… 😔

[![ALOT](https://user-images.githubusercontent.com/16304/211357365-22c436a4-4e30-4f16-b44c-54836987f949.png)](https://knowyourmeme.com/memes/the-alot)
